version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - "3000:5432"
    environment:
      POSTGRES_DB: InferenceApi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  pgdata:
